### ISSUE TITLE
Problematic typo on website installation instructions

### ISSUE THREAD

**Issue by Excuze** [AnyiLin/Pedro-Pathing-Quickstart#5] opened 2024-09-11 20:02 UTC
Hello! My apologies if this is the wrong place to report this, I couldn't find a contact page with a quick perusal.

The homepage of the website that links here (https://pedropathing.com/Pedro+Pathing) has a typo in its alternate, manual installation instructions that causes the build to fail. It's pretty easy to catch and fix but it might be a hiccup for some people, so I figured I'd phone it in.

As pictured, the implementation clause is spelled:
    implementation 'com.fasterxml/jackson.core:***jacson***-databind:2.12.7'
It should be:
    implementation 'com.fasterxml/jackson.core:***jackson***-databind:2.12.7'
<img width="512" alt="typo" src="https://github.com/user-attachments/assets/6678c210-1fee-4afd-bffc-58c428e2eca3">

Thank you! Hope this is the right place. Have a good day.

**Comment by AnyiLin** [comment] 2024-09-12 05:20
Thank you, we will fix this as soon as possible. The issue is fixed within the readme files in the quickstart. If you have any further questions, you can email scottsbots10158@gmail.com

**Comment by Froze-N-Milk** [comment] 2024-10-29 18:15
still not fixed btw

**Comment by Logan-Nash** [comment] 2024-12-05 02:11
New website released which should fix the issue.

**Closed as completed by Logan-Nash** 2024-12-05 02:11 UTC
